// <auto-generated />
using System;
using FinSight.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinSight.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260825042202_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinSight.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("DetailPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("detail_payload");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_entity_id");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("related_entity_type");

                    b.Property<Guid?>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("audit_logs", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Audit_EventType", "\"event_type\" IN ('BatchCreated', 'BatchValidated', 'ReconciliationStarted', 'ReconciliationCompleted', 'ReconciliationFailed', 'ReconciliationDecisionRecorded', 'ExceptionCreated', 'AiQuestionAsked', 'AiToolInvoked', 'AiExplanationRequested', 'AiExplanationFailed', 'AiAssistantFailed')");

                            t.HasCheckConstraint("CHK_Audit_RelatedEntityPair", "(\"related_entity_type\" IS NULL AND \"related_entity_id\" IS NULL) OR (\"related_entity_type\" IS NOT NULL AND \"related_entity_id\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("FinSight.Domain.Entities.BankRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("SourceRecordIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_record_identifier");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_reference");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "SourceRecordIdentifier")
                        .IsUnique()
                        .HasDatabaseName("UQ_Bank_TechDup");

                    b.ToTable("bank_records", (string)null);
                });

            modelBuilder.Entity("FinSight.Domain.Entities.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("BankRecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("bank_record_count");

                    b.Property<string>("BatchLabel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("batch_label");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("created_by");

                    b.Property<int>("PaymentRecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("payment_record_count");

                    b.Property<int>("SettlementRecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("settlement_record_count");

                    b.Property<int>("TotalRecordCount")
                        .HasColumnType("integer")
                        .HasColumnName("total_record_count");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("validation_status");

                    b.HasKey("Id");

                    b.ToTable("batches", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Batch_BankRecordCount", "\"bank_record_count\" >= 0");

                            t.HasCheckConstraint("CHK_Batch_PaymentRecordCount", "\"payment_record_count\" >= 0");

                            t.HasCheckConstraint("CHK_Batch_SettlementRecordCount", "\"settlement_record_count\" >= 0");

                            t.HasCheckConstraint("CHK_Batch_TotalRecordCount", "\"total_record_count\" >= 0");

                            t.HasCheckConstraint("CHK_Batch_ValidationStatus", "\"validation_status\" IN ('Valid', 'Invalid')");
                        });
                });

            modelBuilder.Entity("FinSight.Domain.Entities.NormalizedTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("BankRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_record_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("PaymentRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_record_id");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<Guid?>("SettlementRecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("settlement_record_id");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_reference");

                    b.HasKey("Id");

                    b.HasIndex("BankRecordId");

                    b.HasIndex("PaymentRecordId");

                    b.HasIndex("SettlementRecordId");

                    b.HasIndex("RunId", "TransactionReference")
                        .IsUnique()
                        .HasDatabaseName("UQ_NormalizedTx_Ref");

                    b.ToTable("normalized_transactions", (string)null);
                });

            modelBuilder.Entity("FinSight.Domain.Entities.PaymentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("SourceRecordIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_record_identifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_reference");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "SourceRecordIdentifier")
                        .IsUnique()
                        .HasDatabaseName("UQ_Payment_TechDup");

                    b.ToTable("payment_records", (string)null);
                });

            modelBuilder.Entity("FinSight.Domain.Entities.ReconciliationException", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AiExplanation")
                        .HasColumnType("text")
                        .HasColumnName("ai_explanation");

                    b.Property<DateTime?>("AiExplanationGeneratedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("ai_explanation_generated_at");

                    b.Property<string>("AiSuggestedCategory")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ai_suggested_category");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DiscrepancyDetail")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("discrepancy_detail");

                    b.Property<string>("InvolvedSources")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("involved_sources");

                    b.Property<Guid>("ReconciliationResultId")
                        .HasColumnType("uuid")
                        .HasColumnName("reconciliation_result_id");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ReconciliationResultId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Exception_Result");

                    b.HasIndex("RunId");

                    b.ToTable("reconciliation_exceptions", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Exception_Category", "\"category\" IN ('AmountMismatch', 'DateMismatch', 'MissingRecord', 'DuplicateRecord', 'Unresolved')");
                        });
                });

            modelBuilder.Entity("FinSight.Domain.Entities.ReconciliationResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("NormalizedTransactionId")
                        .HasColumnType("uuid")
                        .HasColumnName("normalized_transaction_id");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reason_code");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<string>("StrategyUsed")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("strategy_used");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedTransactionId")
                        .IsUnique()
                        .HasDatabaseName("UQ_Result_Tx");

                    b.HasIndex("RunId");

                    b.ToTable("reconciliation_results", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Result_Status", "\"status\" IN ('Matched', 'Mismatched', 'Missing', 'Duplicate', 'Unresolved')");
                        });
                });

            modelBuilder.Entity("FinSight.Domain.Entities.ReconciliationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("MatchRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("match_rate");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("TotalReconciliationUnits")
                        .HasColumnType("integer")
                        .HasColumnName("total_reconciliation_units");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.ToTable("reconciliation_runs", null, t =>
                        {
                            t.HasCheckConstraint("CHK_Run_MatchRate", "\"match_rate\" IS NULL OR (\"match_rate\" >= 0 AND \"match_rate\" <= 100)");

                            t.HasCheckConstraint("CHK_Run_Status", "\"status\" IN ('Pending', 'Running', 'Completed', 'Failed')");

                            t.HasCheckConstraint("CHK_Run_TotalUnits", "\"total_reconciliation_units\" >= 0");
                        });
                });

            modelBuilder.Entity("FinSight.Domain.Entities.SettlementRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("SourceRecordIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_record_identifier");

                    b.Property<DateOnly>("TransactionDate")
                        .HasColumnType("date")
                        .HasColumnName("transaction_date");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("transaction_reference");

                    b.HasKey("Id");

                    b.HasIndex("BatchId", "SourceRecordIdentifier")
                        .IsUnique()
                        .HasDatabaseName("UQ_Settlement_TechDup");

                    b.ToTable("settlement_records", (string)null);
                });

            modelBuilder.Entity("FinSight.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("FinSight.Domain.Entities.ReconciliationRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FinSight.Domain.Entities.BankRecord", b =>
                {
                    b.HasOne("FinSight.Domain.Entities.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FinSight.Domain.Entities.NormalizedTransaction", b =>
                {
                    b.HasOne("FinSight.Domain.Entities.BankRecord", null)
                        .WithMany()
                        .HasForeignKey("BankRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinSight.Domain.Entities.PaymentRecord", null)
                        .WithMany()
                        .HasForeignKey("PaymentRecordId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FinSight.Domain.Entities.ReconciliationRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinSight.Domain.Entities.SettlementRecord", null)
                        .WithMany()
                        .HasForeignKey("SettlementRecordId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("FinSight.Domain.Entities.PaymentRecord", b =>
                {
                    b.HasOne("FinSight.Domain.Entities.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FinSight.Domain.Entities.ReconciliationException", b =>
                {
                    b.HasOne("FinSight.Domain.Entities.ReconciliationResult", null)
                        .WithOne()
                        .HasForeignKey("FinSight.Domain.Entities.ReconciliationException", "ReconciliationResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinSight.Domain.Entities.ReconciliationRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinSight.Domain.Entities.ReconciliationResult", b =>
                {
                    b.HasOne("FinSight.Domain.Entities.NormalizedTransaction", null)
                        .WithOne()
                        .HasForeignKey("FinSight.Domain.Entities.ReconciliationResult", "NormalizedTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinSight.Domain.Entities.ReconciliationRun", null)
                        .WithMany()
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinSight.Domain.Entities.ReconciliationRun", b =>
                {
                    b.HasOne("FinSight.Domain.Entities.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("FinSight.Domain.Entities.SettlementRecord", b =>
                {
                    b.HasOne("FinSight.Domain.Entities.Batch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
